CREATE TABLE Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    AccountName VARCHAR(255) NOT NULL UNIQUE,
    Name VARCHAR(255) NOT NULL,
    FirstName VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    DatabaseName VARCHAR(255) NOT NULL
);
