name: Build MAUI Android & iOS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Installer .NET 8 et MAUI
        run: |
          sudo apt update
          sudo apt install -y dotnet-sdk-8.0
          dotnet --version
          dotnet workload install maui-android
          dotnet workload restore

      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l’application Android
        run: |
          cd src/Mobile
          dotnet publish -f net8.0-android -c Release -o out

      - name: Upload du build Android
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: src/Mobile/out

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer .NET 8 et MAUI iOS
        run: |
          dotnet workload install maui-ios
          dotnet workload restore
          dotnet --info

      - name: Build de l’application iOS
        run: |
          cd src/Mobile
          dotnet publish -f net8.0-ios -c Release -o out

      - name: Upload du build iOS
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: src/Mobile/out
