name: Build MAUI Android & iOS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer .NET SDK 8
        run: |
          curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --install-dir $HOME/.dotnet --version 8.0.112
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          echo "$HOME/.dotnet" >> $GITHUB_PATH

      - name: Installer MAUI Android
        run: |
          dotnet workload restore
          dotnet workload install maui-android

      - name: Build Android
        run: |
          cd src/Mobile
          dotnet restore
          dotnet build ../Shared/Shared.csproj -c Release
          dotnet build ../Client/Client.csproj -c Release
          dotnet publish Mobile.Android.csproj -c Release -o out

      - name: Upload Android Build
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: src/Mobile/out

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer .NET SDK 8
        run: |
          brew install --cask dotnet-sdk
          echo "DOTNET_ROOT=/usr/local/share/dotnet" >> $GITHUB_ENV
          echo "/usr/local/share/dotnet" >> $GITHUB_PATH

      - name: Installer MAUI iOS
        run: |
          dotnet workload restore
          dotnet workload install maui-ios

      - name: Build iOS
        run: |
          cd src/Mobile
          dotnet restore
          dotnet build ../Shared/Shared.csproj -c Release
          dotnet build ../Client/Client.csproj -c Release
          dotnet publish Mobile.iOS.csproj -c Release -o out

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: src/Mobile/out
