name: Build MAUI Android & iOS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer .NET SDK 8
        run: |
          curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --install-dir $HOME/.dotnet --version 8.0.112
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          echo "$HOME/.dotnet" >> $GITHUB_PATH

      - name: Installer Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip sdk-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV

      - name: Installer MAUI Android
        run: |
          dotnet workload restore
          dotnet workload install maui-android

      - name: Clean and Build Shared
        run: |
          dotnet clean src/Shared/Shared.csproj
          dotnet restore src/Shared/Shared.csproj
          dotnet build src/Shared/Shared.csproj -c Release --no-parallel

      - name: Clean and Build Client
        run: |
          dotnet clean src/Client/Client.csproj
          dotnet restore src/Client/Client.csproj
          dotnet build src/Client/Client.csproj -c Release --no-parallel

      - name: Clean and Build Android
        run: |
          dotnet clean src/Mobile/Mobile.Android.csproj
          dotnet restore src/Mobile/Mobile.Android.csproj
          dotnet build src/Mobile/Mobile.Android.csproj -c Release --no-parallel
          dotnet publish src/Mobile/Mobile.Android.csproj -c Release -o out

      - name: Upload Android Build
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: src/Mobile/out

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer .NET SDK 8 (macOS)
        run: |
          brew install --cask dotnet-sdk
          echo "DOTNET_ROOT=/usr/local/share/dotnet" >> $GITHUB_ENV
          echo "/usr/local/share/dotnet" >> $GITHUB_PATH

      - name: Installer MAUI iOS
        run: |
          sudo dotnet workload restore
          sudo dotnet workload install maui-ios

      - name: Clean and Build Shared
        run: |
          dotnet clean src/Shared/Shared.csproj
          dotnet restore src/Shared/Shared.csproj
          dotnet build src/Shared/Shared.csproj -c Release --no-parallel

      - name: Clean and Build Client
        run: |
          dotnet clean src/Client/Client.csproj
          dotnet restore src/Client/Client.csproj
          dotnet build src/Client/Client.csproj -c Release --no-parallel

      - name: Update Xcode to latest version
        run: sudo xcode-select --switch /Applications/Xcode_16.0.app/Contents/Developer

      - name: Clean and Build iOS
        run: |
          dotnet clean src/Mobile/Mobile.iOS.csproj
          dotnet restore src/Mobile/Mobile.iOS.csproj
          dotnet build src/Mobile/Mobile.iOS.csproj -c Release --no-parallel
          dotnet publish src/Mobile/Mobile.iOS.csproj -c Release -o out

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: src/Mobile/out
